# This file contains values from Cookiecutter

default_context:
  project_name: "dora"
  project_description: "Awesome `dora` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "TU Berlin UMI-Lab"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.7
  github_name: "lapalap"
  email: "kirill.bykov@campus.tu-berlin.de"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
